# inspo. https://codeberg.org/Ti-mmm/nixos-config/src/branch/main/pkgs/cider3/default.nix
{pkgs, ...}: let
  pname = "Cider";
  version = "3.1.8";

  src = pkgs.fetchurl {
    url = "https://files.sengozhome.losa.dev/cider-v3.1.8-linux-x64.AppImage"; # my basic private webdav server.
    sha256 = "sha256-s1CMYAfDULaEyO0jZguA2bA7D7ogqRR4v/LkMD+luKw=";
  };

  appimageContents = pkgs.appimageTools.extract {inherit pname version src;};
in
  pkgs.appimageTools.wrapType2 {
    inherit pname version src;

    # makeWrapper must be available in build environment
    nativeBuildInputs = [pkgs.makeWrapper];

    extraInstallCommands = ''
      install -m 444 -D ${appimageContents}/${pname}.desktop -t $out/share/applications
      substituteInPlace $out/share/applications/${pname}.desktop \
        --replace 'Exec=AppRun' 'Exec=${pname}'
      cp -r ${appimageContents}/usr/share/icons $out/share
    '';
    # extraInstallCommands = ''
    #   # Desktop entry
    #   install -m 444 -D ${appimageContents}/${pname}.desktop \
    #     -t $out/share/applications

    #   # Icon
    #   install -m 444 -D ${appimageContents}/${pname}.png \
    #     -t $out/share/icons/hicolor/512x512/apps

    #   # Replace the broken autogenerated launcher
    #   rm -f $out/bin/${pname}
    #   makeWrapper ${appimageContents}/usr/lib/Cider/Cider $out/bin/cider
    # '';
  }
